const canvasBlocks = [
 {id:'partners',category:'creacion',icon:'↗',title:'Socios Clave',summary:'Alianzas que hacen posible el catálogo y la experiencia.',detail:'Colaboradores que aportan contenido, derechos, tecnología y acceso a dispositivos.',items:['Artistas y músicos','Sellos discográficos','Editoriales musicales','Podcasters y creadores de contenido','Proveedores de tecnología','Fabricantes de dispositivos y plataformas']},
 {id:'activities',category:'creacion',icon:'◌',title:'Actividades Clave',summary:'Operación, distribución y mejora constante del servicio.',detail:'Acciones que sostienen una plataforma de audio disponible y personalizada.',items:['Desarrollo y mantenimiento de la plataforma','Distribución y reproducción de contenido','Gestión de licencias musicales','Desarrollo de algoritmos de recomendación','Marketing y adquisición de usuarios','Análisis de datos']},
 {id:'resources',category:'creacion',icon:'▦',title:'Recursos Clave',summary:'Activos que habilitan la propuesta de valor.',detail:'Recursos tecnológicos, de contenido y de marca necesarios para ofrecer el servicio.',items:['Plataforma tecnológica','Catálogo de contenido','Algoritmos de recomendación','Datos de usuarios','Marca Spotify','Infraestructura tecnológica']},
 {id:'value',category:'creacion',icon:'✦',title:'Propuesta de Valor',summary:'Audio personal, accesible y disponible en distintos momentos.',detail:'La propuesta combina descubrimiento, variedad de contenido y modalidades de acceso.',items:['Acceso a una gran cantidad de música y podcasts','Escucha personalizada','Recomendaciones basadas en gustos','Plan gratuito con publicidad','Planes Premium','Acceso desde diferentes dispositivos']},
 {id:'relationships',category:'clientes',icon:'◎',title:'Relación con Clientes',summary:'Una experiencia guiada por hábitos y descubrimiento.',detail:'Interacciones digitales orientadas a que cada persona encuentre contenido relevante.',items:['Experiencia personalizada','Recomendaciones automáticas','Playlists personalizadas','Soporte al usuario','Comunicación mediante la aplicación y canales digitales','Descubrimiento de nuevo contenido']},
 {id:'channels',category:'clientes',icon:'⌁',title:'Canales',summary:'Presencia donde las personas escuchan.',detail:'Puntos de acceso que permiten usar el servicio en diferentes contextos y dispositivos.',items:['Aplicación móvil','Aplicación de escritorio','Sitio web','Smart TVs','Consolas','Automóviles','Integraciones con otros dispositivos']},
 {id:'segments',category:'clientes',icon:'◉',title:'Segmentos de Clientes',summary:'Audiencias de escucha, creación y publicidad.',detail:'Grupos con necesidades distintas a los que el modelo busca aportar valor.',items:['Usuarios gratuitos','Usuarios Premium','Estudiantes','Familias','Usuarios individuales','Anunciantes','Creadores y artistas']},
 {id:'costs',category:'finanzas',icon:'−',title:'Estructura de Costos',summary:'Recursos, derechos y operación necesarios para prestar el servicio.',detail:'Costos asociados con el contenido, producto, infraestructura y crecimiento.',items:['Licencias y derechos musicales','Infraestructura tecnológica','Desarrollo de software','Marketing','Personal','Operaciones','Distribución de contenido']},
 {id:'revenue',category:'finanzas',icon:'＋',title:'Fuentes de Ingresos',summary:'Suscripciones y soluciones publicitarias.',detail:'Vías analizadas para capturar valor a partir de las distintas audiencias.',items:['Suscripciones Premium','Publicidad','Planes para usuarios individuales','Planes familiares','Planes para estudiantes','Servicios y soluciones publicitarias']}
];
